In [1]:
import numpy as np
km = np.loadtxt('data/carros-km.txt')
anos = np.loadtxt('data/carros-anos.txt', dtype=int)

km_media = km / (2019 - anos)

D:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in true_divide
  """


In [3]:
quilometragem = None

In [4]:
type(quilometragem)

NoneType

In [6]:
a = 10
c = 'teste '

In [7]:
c + str(a)

'teste 10'

In [8]:
var = 3.141592

In [9]:
int(var)


3

In [10]:
print('Teste, {}'.format('Marcio'))

Teste, Marcio


In [18]:
A = ['Pneus', 'Rodas', ]
B = ['Suspensão']

In [19]:
A + B

['Pneus', 'Rodas', 'Suspensão']

In [45]:
carros = [
    [
        'Jetta Variant',
        'Motor 4.0 Turbo',
        2003,
        False,
        ['Rodas de liga', 'Travas elétricas', 'Piloto automático']
    ],
    [
        'Passat',
        'Motor Diesel',
        1991,
        True,
        ['Central multimídia', 'Teto panorâmico', 'Freios ABS']
    ]
]


In [56]:
carros.append('Pampa')
carros.pop()

'Pampa'

In [58]:
carros2 = carros.copy()

In [59]:
carros2.append('Corsa')

In [61]:

carros

[['Jetta Variant',
  'Motor 4.0 Turbo',
  2003,
  False,
  ['Rodas de liga', 'Travas elétricas', 'Piloto automático']],
 ['Passat',
  'Motor Diesel',
  1991,
  True,
  ['Central multimídia', 'Teto panorâmico', 'Freios ABS']],
 'Pampa']

In [62]:
Acessorios = [
    'Rodas de liga', 
    'Travas elétricas', 
    'Piloto automático',
    'Bancos de couro',
    'Ar condicionado'
]

In [66]:
[i ** 2 for i in range(10) if i < 5]

[0, 1, 4, 9, 16]

In [85]:
import numpy as np

km = np.loadtxt(fname = 'data/carros-km.txt', dtype = int)

In [88]:
np_array = np.arange(1000000)

In [90]:
py_list = list(range(1000000))

In [94]:
%time for _ in range(100): np_array *= 2

Wall time: 147 ms


In [95]:
%time for _ in range(100): py_list = [x * 2 for x in py_list]

Wall time: 21.6 s


In [96]:
dados = np.array([])

In [102]:
peso = np.array([106.0, 68.5, 75.0])
altura = np.array([1.9, 1.53, 1.75])

In [108]:
IMC = peso / altura ** 2
IMC

array([29.36288089, 29.26224956, 24.48979592])

In [65]:
import numpy as np

contador=  np.arange(10)

km = np.array([44410., 5712., 37123., 0., 25757.])
anos = np.array([2003, 1991, 1990, 2019, 2006])

print(km)
print(anos)
print(km/(2019-anos))


[44410.  5712. 37123.     0. 25757.]
[2003 1991 1990 2019 2006]
[2775.625       204.         1280.10344828           nan 1981.30769231]


D:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: RuntimeWarning: invalid value encountered in true_divide
  # Remove the CWD from sys.path while we load stuff.


In [3]:

dados = np.array([[44410., 5712., 37123., 0., 25757.],
                 [2003, 1991, 1990, 2019, 2006]])
km_media = dados[0] / (2019 - dados[1])
# print(km_media)

print(dados,'\n')
print(dados[:, dados[1]>2000])


[[44410.  5712. 37123.     0. 25757.]
 [ 2003.  1991.  1990.  2019.  2006.]] 

[[44410.     0. 25757.]
 [ 2003.  2019.  2006.]]


D:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


In [14]:
dados.reshape(5,2)

array([[44410.,  5712.],
       [37123.,     0.],
       [25757.,  2003.],
       [ 1991.,  1990.],
       [ 2019.,  2006.]])

In [26]:
dados_new = dados.copy()

In [27]:
dados_new.resize((3,5), refcheck=False)

In [28]:

dados_new[2] = dados_new[0] / (2019-dados_new[1])

D:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [30]:
dados_new

array([[44410.        ,  5712.        , 37123.        ,     0.        ,
        25757.        ],
       [ 2003.        ,  1991.        ,  1990.        ,  2019.        ,
         2006.        ],
       [ 2775.625     ,   204.        ,  1280.10344828,            nan,
         1981.30769231]])

In [50]:
print(dados)
print('')
print(dados[:,dados[1] > 2000])

[[44410.  5712. 37123.     0. 25757.]
 [ 2003.  1991.  1990.  2019.  2006.]]

[[44410.     0. 25757.]
 [ 2003.  2019.  2006.]]


In [47]:
dados[:, dados[1] > 2000]

array([[44410.,     0., 25757.],
       [ 2003.,  2019.,  2006.]])

In [59]:
anos = np.loadtxt(fname = 'data/carros-anos.txt', dtype = int)
km = np.loadtxt(fname = 'data/carros-km.txt')
valor = np.loadtxt(fname = 'data/carros-valor.txt')

In [71]:
dataset = np.column_stack((anos, km, valor))
np.mean(dataset[:, 1:], axis=0)
teste = np.std(dataset[:,1], axis=0)
print(teste)

dataset[:,1:].sum(axis = 0)

39859.82699005149


array([11480849.        , 25531812.37999999])

In [66]:
dataset

array([[2.0030000e+03, 4.4410000e+04, 8.8078640e+04],
       [1.9910000e+03, 5.7120000e+03, 1.0616194e+05],
       [1.9900000e+03, 3.7123000e+04, 7.2832160e+04],
       [2.0190000e+03, 0.0000000e+00, 1.2454907e+05],
       [2.0060000e+03, 2.5757000e+04, 9.2612100e+04],
       [2.0120000e+03, 1.0728000e+04, 9.7497730e+04],
       [2.0190000e+03, 0.0000000e+00, 5.6445200e+04],
       [2.0090000e+03, 7.7599000e+04, 1.1231044e+05],
       [2.0100000e+03, 9.9197000e+04, 1.2071627e+05],
       [2.0110000e+03, 3.7978000e+04, 7.6566490e+04],
       [2.0020000e+03, 1.2859000e+04, 7.1647590e+04],
       [2.0070000e+03, 8.0520000e+03, 7.3919530e+04],
       [2.0010000e+03, 8.9773000e+04, 1.1273299e+05],
       [2.0190000e+03, 0.0000000e+00, 5.3183380e+04],
       [2.0090000e+03, 4.1457000e+04, 1.2748842e+05],
       [2.0160000e+03, 1.1560700e+05, 5.9910400e+04],
       [2.0120000e+03, 4.6449000e+04, 6.1118590e+04],
       [2.0190000e+03, 0.0000000e+00, 8.8552390e+04],
       [2.0160000e+03, 3.708

In [75]:
idades = np.array([10, 23, 45, 34, 25])
np.mean(idades)

27.4

In [80]:
mean(idades)

NameError: name 'mean' is not defined